title: Aigor's dev blog | Small notes about software development
description: Small notes about software development made by Aigor.
flikr_url: https://www.flickr.com/photos/137534701@N07/
500px_url: https://500px.com/aigor
